events {
	worker_connections 1024;
}
http {
	charset utf-8;


	server {
		listen 80 default_server;
		location / {
			return 301  https://$host$request_uri;
		}
	}

	server {
		listen 443 ssl;
		ssl_certificate /etc/ssl/nginx.crt;
		ssl_certificate_key /etc/ssl/nginx.key;

		location /api {
			proxy_pass http://<host>:27415/api;
		}
		
		location /db {
			proxy_pass http://<host>:6379;
		}		

		location / {
			proxy_pass http://<host>:8086;
		}	
	}
}
